# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Triage < Formula
  desc "A Go CLI tool for agentic use."
  homepage "https://github.com/monitaurus/triage"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/monitaurus/triage/releases/download/v1.0.0/triage_Darwin_x86_64.tar.gz"
      sha256 "088e3798ab35db160f84c505aa8b3ad6646fe1d1d445eee8947ee31ccef3b86c"

      define_method(:install) do
        bin.install "triage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/monitaurus/triage/releases/download/v1.0.0/triage_Darwin_arm64.tar.gz"
      sha256 "54777579addf1fc60325fcb3a16db9f09ac818c172fc60b832c709b727fb979a"

      define_method(:install) do
        bin.install "triage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/monitaurus/triage/releases/download/v1.0.0/triage_Linux_x86_64.tar.gz"
      sha256 "f0e145c4f94d8344dff46c68b445cd93ef2d636f6645d484709cec179195b074"
      define_method(:install) do
        bin.install "triage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/monitaurus/triage/releases/download/v1.0.0/triage_Linux_arm64.tar.gz"
      sha256 "d7e3c91e33d0c0a61bb70bd242f53fd2cfd9ade0164ff6d2ea62aa1afbd4b844"
      define_method(:install) do
        bin.install "triage"
      end
    end
  end
end
