# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Triage < Formula
  desc "A Go CLI tool for agentic use."
  homepage "https://github.com/monitaurus/triage"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/monitaurus/triage/releases/download/v1.0.0/triage_Darwin_x86_64.tar.gz"
      sha256 "ac4a2c09b78401c2e76fecf1b9c97454bdb95e57ca69d7401a3816e33b9e57d2"

      define_method(:install) do
        bin.install "triage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/monitaurus/triage/releases/download/v1.0.0/triage_Darwin_arm64.tar.gz"
      sha256 "94356ab73ce69195126679596efec628ddf7a0fb45bd985014e5313323c7d5ef"

      define_method(:install) do
        bin.install "triage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/monitaurus/triage/releases/download/v1.0.0/triage_Linux_x86_64.tar.gz"
      sha256 "092ba9169ad6912e2aba20cf3872a20d3865832fefdc971ff21542d961732179"
      define_method(:install) do
        bin.install "triage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/monitaurus/triage/releases/download/v1.0.0/triage_Linux_arm64.tar.gz"
      sha256 "fb298b83f44b0108c79bd28a31961466a8815271ea6817df839189cd51f32899"
      define_method(:install) do
        bin.install "triage"
      end
    end
  end
end
